interview_data = {
    "UT Intellectual Unit - YYYYMMDD_Lastname_Firstname": "20190920_Whaley_Seemona-Daniel",
    "APPL Interview - Original Filename": "",
    "Title": "Interview with Seemona and Daniel Whaley, 2019-09-20",
    "Interview Start TC": "0:00:32",
    "Interview Stop TC": "0:57:34",
    "License": "Creative Commons Attribution 4.0 International License \nhttps://creativecommons.org/licenses/by/4.0",
    "Access Note": "",
    "Narrator Name": "Whaley, Seemona",
    "Narrator Name 2": "Whaley, Daniel",
    "Narrator Name 3": "",
    "Interviewer Name": "Kaufman, Casey",
    "Date Recorded": "9/20/2019",
    "Location Recorded": "John C. Hodges Library, University of Tennessee, Knoxville",
    "Narrator Location Recorded": "John C. Hodges Library, University of Tennessee, Knoxville",
    "AAT Format ": "motion pictures (visual works) http://vocab.getty.edu/aat/300136900",
    "Abstract": "Interview with Seemona and Daniel Whaley, former residents of Gatlinburg. The Whaley's discuss the feeling at the time before the fire had become widespread. They also go into detail about the harrowing efforts to evacuate off a mountain that wass engulfed in the fire. Reflections about community relations and how Gatlinburg began to slowly recover are also touched upon.",
    "Narrator Class 1": "Individuals (tourists or locals) directly affected by the fire",
    "Narrator Class 2": "",
    "LCSH_Topic_1": "Teachers",
    "LCSH_Topic_2": "Evacuation of civilians",
    "LCSH_Topic_3": "",
    "LCSH_Geo_1": "",
    "LCSH_Geo_2": "",
    "LCSH_Name_1": "",
    "LCSH_Name_2": "",
    "Interview_Question_1": "Can you state your names and tell us about your history in Gatlinburg?",
    "Interview_Question_1_TC": "0:01:27",
    "Interview_Question_2": "Can you tell us about your occupation in Gatlinburg?",
    "Interview_Question_2_TC": "0:03:24",
    "Interview_Question_3": "Can you tell us about your other roles in the community in Gatlinburg?",
    "Interview_Question_3_TC": "0:05:00",
    "Interview_Question_4": "Can you recall anything about the days leading up to the fire?",
    "Interview_Question_4_TC": "0:06:20",
    "Interview_Question_5": "At what point did you become concerned?",
    "Interview_Question_5_TC": "0:08:35",
    "Interview_Question_6": "So you took your son to the high school?",
    "Interview_Question_6_TC": "0:10:39",
    "Interview_Question_7": "This was in the afternoon?",
    "Interview_Question_7_TC": "0:11:01",
    "Interview_Question_8": "When you were at the school, what was the general feeling?",
    "Interview_Question_8_TC": "0:11:44",
    "Interview_Question_9": "After you went back home, can you tell me about what transpired that evening?",
    "Interview_Question_9_TC": "0:12:51",
    "Interview_Question_10": "How did you feel at that point in the evacuation?",
    "Interview_Question_10_TC": "0:21:16",
    "Interview_Question_11": "You hadn't even made it through the path of the fire yet?",
    "Interview_Question_11_TC": "0:28:41",
    "Interview_Question_12": "So where do you evacuate to?",
    "Interview_Question_12_TC": "0:29:53",
    "Interview_Question_13": "When you get to your mother's house, what are you thinking?",
    "Interview_Question_13_TC": "0:32:17",
    "Interview_Question_14": "You returned to Gatlinburg after 3 days?\n",
    "Interview_Question_14_TC": "0:33:41",
    "Interview_Question_15": "Where did you go after leaving your mother's house?",
    "Interview_Question_15_TC": "0:36:38",
    "Interview_Question_16": "How did you start that first day back at school? What was is like bringing all the kids back together?",
    "Interview_Question_16_TC": "0:44:30",
    "Interview_Question_17": "Can you tell me about the decision to move after the fire?",
    "Interview_Question_17_TC": "0:46:04",
    "Interview_Question_18": "How has this experience affected you emotionally, both as a family and an individual?",
    "Interview_Question_18_TC": "0:48:18",
    "Interview_Question_19": "Have you thought about making any provisions in case an emergency happens again?",
    "Interview_Question_19_TC": "0:52:30",
    "Interview_Question_20": "Is there anything else that you would like to add?",
    "Interview_Question_20_TC": "0:57:15",
    "Interview_Question_21": "",
    "Interview_Question_21_TC": "",
    "Interview_Question_22": "",
    "Interview_Question_22_TC": "",
    "Interview_Question_23": "",
    "Interview_Question_23_TC": "",
    "Interview_Question_24": "",
    "Interview_Question_24_TC": "",
    "Interview_Question_25": "",
    "Interview_Question_25_TC": "",
    "Interview_Question_26": "",
    "Interview_Question_26_TC": "",
    "Interview_Question_27": "",
    "Interview_Question_27_TC": "",
    "Interview_Question_28": "",
    "Interview_Question_28_TC": "",
    "Interview_Question_29": "",
    "Interview_Question_29_TC": "",
    "Interview_Question_30": "",
    "Interview_Question_30_TC": "",
    "Interview_Question_31": "",
    "Interview_Question_31_TC": "",
    "Interview_Question_32": "",
    "Interview_Question_32_TC": "",
    "Interview_Question_33": "",
    "Interview_Question_33_TC": "",
    "Interview_Question_34": "",
    "Interview_Question_34_TC": "",
    "Interview_Question_35": "",
    "Interview_Question_35_TC": "",
    "Interview_Question_36": "",
    "Interview_Question_36_TC": "",
    "Interview_Question_37": "",
    "Interview_Question_37_TC": "",
    "Interview_Question_38": "",
    "Interview_Question_38_TC": "",
    "Interview_Question_39": "",
    "Interview_Question_39_TC": "",
    "Interview_Question_40": "",
    "Interview_Question_40_TC": "",
    "Interview_Question_41": "",
    "Interview_Question_41_TC": "",
    "Interview_Question_42": "",
    "Interview_Question_42_TC": "",
    "Interview_Question_43": "",
    "Interview_Question_43_TC": "",
    "Interview_Question_44": "",
    "Interview_Question_44_TC": "",
    "Interview_Question_45": "",
    "Interview_Question_45_TC": "",
    "Interview_Question_46": "",
    "Interview_Question_46_TC": "",
    "Interview_Question_47": "",
    "Interview_Question_47_TC": "",
    "Interview_Question_48": "",
    "Interview_Question_48_TC": "",
    "Interview_Question_49": "",
    "Interview_Question_49_TC": "",
    "Interview_Question_50": "",
    "Interview_Question_50_TC": "",
    "Interview_Question_51": "",
    "Interview_Question_51_TC": "",
    "Interview_Question_52": "",
    "Interview_Question_52_TC": "",
    "Interview_Question_53": "",
    "Interview_Question_53_TC": "",
    "Interview_Question_54": "",
    "Interview_Question_54_TC": "",
    "Interview_Question_55": "",
    "Interview_Question_55_TC": "",
    "Interview_Question_56": "",
    "Interview_Question_56_TC": "",
    "Interview_Question_57": "",
    "Interview_Question_57_TC": "",
    "Interview_Question_58": "",
    "Interview_Question_58_TC": "",
    "Interview_Question_59": "",
    "Interview_Question_59_TC": "",
    "Interview_Question_60": "",
    "Interview_Question_60_TC": "",
    "Interview_Question_61": "",
    "Interview_Question_61_TC": "",
    "Interview_Question_62": "",
    "Interview_Question_62_TC": "",
    "Interview_Question_63": "",
    "Interview_Question_63_TC": "",
    "Interview_Question_64": "",
    "Interview_Question_64_TC": "",
    "Interview_Question_65": "",
    "Interview_Question_65_TC": "",
    "Interview_Question_66": "",
    "Interview_Question_66_TC": "",
    "Interview_Question_67": "",
    "Interview_Question_67_TC": "",
    "Interview_Question_68": "",
    "Interview_Question_68_TC": "",
    "Interview_Question_69": "",
    "Interview_Question_69_TC": "",
    "Interview_Question_70": "",
    "Interview_Question_70_TC": "",
    "Interview_Question_71": "",
    "Interview_Question_71_TC": "",
    "Interview_Question_72": "",
    "Interview_Question_72_TC": "",
    "Chapter_1": "",
    "Chapter_1_TC": "",
    "Chapter_2": "",
    "Chapter_2_TC": "",
    "Chapter_3": "",
    "Chapter_3_TC": "",
    "Chapter_4": "",
    "Chapter_4_TC": "",
    "Chapter_5": "",
    "Chapter_5_TC": "",
    "Chapter_6": "",
    "Chapter_6_TC": "",
    "Chapter_7": "",
    "Chapter_7_TC": "",
    "Chapter_8": "",
    "Chapter_8_TC": "",
    "Chapter_9": "",
    "Chapter_9_TC": "",
    "Chapter_10": "",
    "Chapter_10_TC": "",
    "Chapter_11": "",
    "Quote from Interview": '"That\'s where it looked like lava running up the mountain. You could see the fire going uphill."',
    "Location_1\n": "Chalet Village North, Gatlinburg, TN",
    "Location_1_Coordinates": "35.7232049, -83.5277175",
    "Location_1_TC": "00:12:50 - 00:26:45",
    "Location_2": "Pi Beta Phi Elementary",
    "Location_2_Coordinates": "35.7117, -83.5121015",
    "Location_2_TC": "00:09:18 - 0012:50",
    "Location_3": "The Spur (US-321/US 441 S)",
    "Location_3_Coordinates": "35.744143, -83.520302",
    "Location_3_TC": "00:28:18 - 00:32:16",
    "Location_4": "",
    "Location_4_Coordinates": "",
    "Location_4_TC": "",
    "Location_5": "",
    "Location_5_Coordinates": "",
    "Location_5_TC": "",
    "Location_6": "",
    "Location_6_Coordinates": "",
    "Location_6_TC": "",
    "Date of Birth": "",
    "Birthplace": "",
    "Length of Time in Gatlinburg/East Tennessee": "",
    "Education": "",
    "Occupational Experience": "",
    "Other Community Involvement": "",
    "Other Life Info": "",
    "Disclaimer": "The Rising from the Ashes Oral History Project collects personal accounts of the Chimney Tops II Wildfires of 2016, and The University of Tennessee holds no liability for statements made in the recordings. These accounts reflect the opinions of the narrators, and thus they are subjective and should not be considered verified or comprehensive. Oral history interviews may be used alongside other primary and secondary source materials to gain a fuller understanding of historical events.",
    "Privacy/Defamation concern?": "",
    "Appearance Release": "",
}
